


# Uncomment the next line to define a global platform for your project
 platform :ios, '14.0'

target 'YoWagerqueSlotinnovateNo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

   pod 'IQKeyboardManager'
   pod 'Adjust','4.38.4'
   pod 'KSCrash', '~> 2.0.0-rc.1'
   
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
        config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
      end
    end
  end
end
